msm: camera: isp: fix -Wpointer-to-int-cast
Fixes:
drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_fe_ver1.c:399:20: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'uint32_t *' (aka 'unsigned int *') [-Werror,-Wpointer-to-int-cast]
        cam_cpas_reg_read((uint32_t)soc_private->cpas_handle,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/media/platform/msm/camera_floral/cam_isp/isp_hw_mgr/isp_hw/vfe_hw/vfe_top/cam_vfe_fe_ver1.c:403:20: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'uint32_t *' (aka 'unsigned int *') [-Werror,-Wpointer-to-int-cast]
        cam_cpas_reg_read((uint32_t)soc_private->cpas_handle,
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Clang compiler show error messages while casting pointer into integer.
The folder of `drivers/media/platform/msm/camera_floral` is clone version of
C2F2 and S5 from since commit a605022835ff ("Separate camera").
Qualcomm fixed this issue in commit ced9727afdd6 ("msm: ais: Sync to
latest mobile camera"). To copy the solution can avoid this issue.

Bug: 171827315
Signed-off-by: lucaswei <lucaswei@google.com>
Change-Id: I1f85585591a1da0bc0d448c94367bee2aa47c91d