hwtracing: coresight: Export symbols required for coresight-link-sink-tmc.ko
ERROR: "barrier_pkt" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!
ERROR: "coresight_timeout" [drivers/hwtracing/coresight/coresight-link-sink-tmc.ko] undefined!

Bug: 143362906
Test: build, boot test, all devices  still probe.

Change-Id: I7588d23edd869a0ecaec0a5a887f1a14f6ed6288
Signed-off-by: Hridya Valsaraju <hridya@google.com>