GKI: power: qpnp: Export symbols lock_votable and unlock_votable
Fixes errors:
ERROR: "unlock_votable" [drivers/power/supply/qcom/qpnp-smb5-charger.ko] undefined!
ERROR: "lock_votable" [drivers/power/supply/qcom/qpnp-smb5-charger.ko] undefined!

Bug: 147006288
Bug: 147274729
Change-Id: Ibb6e7779551e1642255e6f892f31e6153676b13e
Fixes: 1aa512d0241a ("GKI: power: qpnp: add exports for modularizing")
Signed-off-by: Kyle Tso <kyletso@google.com>