misc: Fix statement expression in macro
Newer version of Clang update for compound punctuation
tokens that are split across macro expansions or split by whitespace.
Fix this expansion to avoid build breakage on faceauth driver.

./private/msm-google/drivers/misc/faceauth.c:201:3: error: '(' and '{' tokens introducing statement expression appear in different macro expansion contexts [-Werror,-Wcompound-token-split-by-macro]
                ATRACE_BLOCK("el2_faceauth_process", {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./private/msm-google/include/trace/events/systrace.h:91:2: note: expanded from macro 'ATRACE_BLOCK'
        (block);                        \
        ^
./private/msm-google/drivers/misc/faceauth.c:201:40: note: '{' token is here
                ATRACE_BLOCK("el2_faceauth_process", {
                                                     ^
Bug: 176825272
Link: https://reviews.llvm.org/D86751
Signed-off-by: Lucas Wei <lucaswei@google.com>
Change-Id: I9d0e2dc469bba65853fdc1fbd5ba1d87505353ab