rpmsg: glink: Fix compilation error in qcom_glink_native_rx()
Commit 223ded0a6132 ("rpmsg: Correctly report glink wake interrupts to
PM subsystem") accidentally introduced the following compilation error:

private/msm-google/drivers/rpmsg/qcom_glink_native.c:1312:24: error: use of undeclared identifier 'irq'
                pm_system_irq_wakeup(irq);
                                     ^
1 error generated.

Fix this by obtaining the irq number from the qcom_glink structure.

Bug: 261236655
Fixes: 223ded0a6132 ("rpmsg: Correctly report glink wake interrupts to PM subsystem")
Change-Id: I96be5796e5b81a2736bf5f2dd5014c0dd8450c35
Signed-off-by: Isaac J. Manjarres <isaacmanjarres@google.com>