dsi: panel: fix -Wbitwise-conditional-parentheses
Fixes the warning:
drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:3227:33: error: operator
'?:' has lower precedence than '|'; '|' will be evaluated first
[-Werror,-Wbitwise-conditional-parentheses]
m.timing.v_sync_polarity ?
~~~~~~~~~~~~~~~~~~~~~~~~ ^

drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:3227:33: note: place
parentheses around the '|' expression to silence this warning
m.timing.v_sync_polarity ?
                        ^
                       )
drivers/gpu/drm/msm/dsi-staging/dsi_panel.c:3227:33: note: place
parentheses around the '?:' expression to evaluate it first
m.timing.v_sync_polarity ?
                        ^
(

This was very obviously meant to be a bitwise or of two different
bitmasks.

Bug: 149786337
Fixes: commit e27f1c211100 ("drm/msm/dsi-staging: implement get_timings")
Change-Id: Idc2b769ac91f2e5fb2fbf4c845fa7141f7f1145b
Cc: Harpreet "Eli" Sangha <eliptus@google.com>
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>