Revert "arm64/dts: b1c1: add easel"
Fixes following build errors:

  Error: arch/arm64/boot/dts/google/sdm845-b1c1-easel.dtsi:21.1-7
         Label or path pcie1 not found
  Error: arch/arm64/boot/dts/google/sdm845-b1c1-easel.dtsi:156.1-17
         Label or path qupv3_se3_2uart not found

This reverts commit 5d32092d32f70d6203c6fd531bf6c770a71a5a9b.

Change-Id: I79085546ed19c62b61cb0024ef605b35af14a9cf