drivers: usb: gadget: export some symbols required for usb_f_qdss.ko
ERROR: "usb_bam_alloc_fifos" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!
ERROR: "usb_bam_connect" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!
ERROR: "get_qdss_bam_info" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!
ERROR: "usb_bam_free_fifos" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!
ERROR: "usb_bam_disconnect_pipe" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!

Bug: 143362906
Test: build, boot_test, all devices still probe.

Change-Id: I2320b7635e7a51adb9ab7295f47ec820f53949f1
Signed-off-by: Hridya Valsaraju <hridya@google.com>