misc: fix compile error in access_ramoops if not module
Add __exit to the access_ramoops_remove so that if the
driver is not compiled as a module the compiler will not
throw a warning.

drivers/misc/access_ramoops.c:205:13: error: 'access_ramoops_remove'
defined but not used [-Werror=unused-function]

Bug: 37554629
Change-Id: I3c6dc73f719a25cdb652c0ee1d638a75f72c7195
Signed-off-by: Patrick Tjin <pattjin@google.com>