GKI: fdt: export symbols required by modules
Export symbol for modulized drivers.

ERROR: "of_fdt_get_ddrrank" [techpack/video/msm/msm-vidc.ko] undefined!
ERROR: "of_fdt_get_ddrhbb" [techpack/display/msm/msm_drm.ko] undefined!
ERROR: "of_fdt_get_ddrrank" [techpack/display/msm/msm_drm.ko] undefined!
ERROR: "of_fdt_get_ddrhbb" [drivers/gpu/msm/msm_adreno.ko] undefined!

Bug: 151601060
Bug: 151568484
Change-Id: I3a20d333ed4b6450d3721d6ae191fc31be2033ed
Signed-off-by: lucaswei <lucaswei@google.com>