touch/fts: Fix #include to avoid No such file error
Switch #include from angle-bracket form to quote form as the path is
relative to ftsTest.c

Previously, in-tree builds failed with the following error message:

drivers/input/touchscreen/stm/fts_lib/ftsTest.c:48:27: fatal error: ../fts_limits.h: No such file or directory
 #include <../fts_limits.h>
                           ^

Out-of-tree builds succeeded because for those builds, the build system
adds -I<path> to CFLAGS where <path> points to the directory that
contains the source file that is currently being compiled.

Change-Id: I0bf920303f1fd04c76c2cf121daa680205404d94
Signed-off-by: Daniel Mentz <danielmentz@google.com>