gbms_storage: fix unused argument
gbms_storage.c:1022:22: error: data argument not used by format string
     [-Werror,-Wformat-extra-args]
        seq_printf(s, "\n", data[i]);
                      ~~~~  ^

Bug: 175172404
Change-Id: If63eeffbb8340e84d73006cabf3101417b8f3a82
Signed-off-by: Patrick Tjin <pattjin@google.com>
Signed-off-by: Ken Tsou <kentsou@google.com>
(cherry picked from commit 744fb27e6d6631d851cf9da84b2cc394fd0c8bce)