iommu: arm-smmu: Use bitwise AND operator to mask
Previously, Clang printed this error message

drivers/iommu/arm-smmu.c:4888:64:
error: use of logical '&&' with constant
      operand [-Werror,-Wconstant-logical-operand]
        if ((iommudata->actlr >> QSMMUV500_ACTLR_DEEP_PREFETCH_SHIFT) &&
                                                                      ^
/drivers/iommu/arm-smmu.c:4888:64:
note: use '&' for a bitwise operation
        if ((iommudata->actlr >> QSMMUV500_ACTLR_DEEP_PREFETCH_SHIFT) &&
                                                                      ^~
                                                                      &

I assume that the author meant to use the & operator instead of the &&
operator to apply a mask.

Change-Id: Ie7af0111667bc9093d6e0a65eea98751faf8b594
Fixes: 233014885b94 ("iommu: Support MMU500 Deep Prefetch errata workaround")
Signed-off-by: Daniel Mentz <danielmentz@google.com>