airbrush: tmu: isr: fix -Wpointer-to-int-cast
drivers/misc/airbrush/tmu/isr.c:81:18: error: cast to smaller integer type 'u32' (aka 'unsigned int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
        u32 intnc_val = (u32)data;
                        ^~~~~~~~~

According to abc_pcie_irq_handler() @ drivers/mfd/abc-pcie.c,
the value passed into data is a `u64` instead of an
`enum abc_msi_mst_t`. The `intnc_val` is a value read from a 4-byte
hardware register, so that it is casted to a `u32` finally
in ab_tmu_isr_notify.

Bug: 171827315
Signed-off-by: lucaswei <lucaswei@google.com>
Change-Id: I1a00e0df7ec66a8b4558edd37df1801f6a75cfc2