iommu/arm-smmu: don't log mask when skipping SMR mask sanity check
Fixes this -Werror=maybe-uninitialized bug when enabling
CONFIG_DYNAMIC_DEBUG:

/include/linux/dynamic_debug.h:86:3:
error: 'mask' may be used uninitialized in this function
[-Werror=maybe-uninitialized]
   __dynamic_dev_dbg(&descriptor, dev, fmt, \
   ^
/drivers/iommu/arm-smmu.c:3428:17:
note: 'mask' was declared here
   u32 smr, sid, mask;
                 ^
This bug was introduced in 8eb33e4b1172d.

Bug: 37354395
Change-Id: Ib59e36dd681e0b5c2857e17020d3204f8f4ef1a0
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>