drivers: usb: gadget: Export symbol required for usb_f_qdss.ko
ERROR: "msm_data_fifo_config" [drivers/usb/gadget/function/usb_f_qdss.ko] undefined!

Bug: 143362906
Test: build, boot test, all devices still probe.

Signed-off-by: Hridya Valsaraju <hridya@google.com>
Change-Id: I2c01869ce23cc745755ca0e98735a611342bdf6b