ipu: ipu-adapter-ab-mfd: Fix -Wpointer-to-int-cast
Fix:
drivers/misc/ipu/ipu-adapter-ab-mfd.c:539:23: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'void *' [-Werror,-Wvoid-pointer-to-int-cast]
        uint32_t intnc_val = (uint32_t)data;
                             ^~~~~~~~~~~~~~
drivers/misc/ipu/ipu-adapter-ab-mfd.c:588:6: error: cast to smaller integer type 'uint32_t' (aka 'unsigned int') from 'uint32_t *' (aka 'unsigned int *') [-Werror,-Wpointer-to-int-cast]
        if ((uint32_t)buffer_vaddr % sizeof(uint32_t) != 0) {
            ^~~~~~~~~~~~~~~~~~~~~~

Fix `uint32_t intnc_val = (uint32_t)data;` with enum data type
replacement to pass compiling check.

Fix `(uint32_t)buffer_vaddr % sizeof(uint32_t) != 0` with unsigned
long to avoid data length truncation.
The ipu_adapter_ab_mfd_atomic_sync32_shared_memory() is used to do
an atomic 32bit read or write of the ring buffers used to communicate
with the RISC-V control processor that manages the job queues for the IPU.
The intent of this code is to check that the address to read or
write is 32bit aligned.

Bug: 171827315
Signed-off-by: lucaswei <lucaswei@google.com>
Change-Id: I90c11c5d9d56734a6fbc4e6838cf39983c8697ff